# This file was generated by Spago2Nix

{ pkgs ? import <nixpkgs> {} }:

let
  inputs = {

    "arrays" = pkgs.stdenv.mkDerivation {
        name = "arrays";
        version = "v6.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-arrays.git";
          rev = "24ac35d3598af6bfb5e479d313f9493ab4d62984";
          sha256 = "1jcjvqyzbk6677f80a91fqwd8pkqza0w2ksk65wb078iffxdr5vn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "bifunctors" = pkgs.stdenv.mkDerivation {
        name = "bifunctors";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-bifunctors.git";
          rev = "a31d0fc4bbebf19d5e9b21b65493c28b8d3fba62";
          sha256 = "0xc2hf8ccdgqw3m9qcmr38kmzv05fsxvakd07wyrqshvkzg3xn0d";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "console" = pkgs.stdenv.mkDerivation {
        name = "console";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-console.git";
          rev = "56cfd5294acb79758cf30b357751f624650f18e3";
          sha256 = "0a93yd5arqjl5l5a3fwandxm78s2lypdbf1kp2dxgw0gl29qqb6p";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "const" = pkgs.stdenv.mkDerivation {
        name = "const";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-const.git";
          rev = "3a3a4bdc44f71311cf27de9bd22039b110277540";
          sha256 = "0aq9qjbrvf8mf8hmas6imv4mg6n3zi13hkf449ns1hn12lw8qv4g";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "contravariant" = pkgs.stdenv.mkDerivation {
        name = "contravariant";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-contravariant.git";
          rev = "ae1a765f7ddbfd96ae1f12e399e46d554d8e3b38";
          sha256 = "029hb8i3n4759x4gc06wkfgr7wim5x1w5jy2bsiy42n0g731h5qc";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "control" = pkgs.stdenv.mkDerivation {
        name = "control";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-control.git";
          rev = "e3add624f8dacb4d6bec6d9ed682df692e197b5b";
          sha256 = "15lilq9hhr3ycg8cz7pdb75sx0lbhgfv7scn0hwa3ss95fs5y40d";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "convertable-options" = pkgs.stdenv.mkDerivation {
        name = "convertable-options";
        version = "v1.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/natefaubion/purescript-convertable-options";
          rev = "58728f24d9a5f28e359b4e7940b347c80cb56c6a";
          sha256 = "1i8l45hnid9xw86s5mig1hk3mwkchl5m99z48y2xfgivv94j6pgw";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "datetime" = pkgs.stdenv.mkDerivation {
        name = "datetime";
        version = "v5.0.2-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-datetime.git";
          rev = "0212f4cb693ca6e4361a09462180a5bc3a9e0552";
          sha256 = "0fbniji09f7j9xciw6i7a6swglyrr2hp2dsfbg97q5qyc88l6f7d";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "distributive" = pkgs.stdenv.mkDerivation {
        name = "distributive";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-distributive.git";
          rev = "11f3f87ca5720899e1739cedb58dd6227cae6ad5";
          sha256 = "0788znmdyh6b1c9pln624ah397l88xmd3fxlxiy3z1qy8bzr4r54";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "effect" = pkgs.stdenv.mkDerivation {
        name = "effect";
        version = "v3.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-effect.git";
          rev = "69ba78cd96a27a0af6a723d255dc05a32c6eaa43";
          sha256 = "12nfc2iz7n9b0k3fmlyk2a6xsjjix7grb9lnc1fi8315db90l9xi";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "either" = pkgs.stdenv.mkDerivation {
        name = "either";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-either.git";
          rev = "c1a1af35684f10eecaf6ac7d38dbf6bd48af2ced";
          sha256 = "18dk159yyv7vs0xsnh9m5fajd7zy6zw5b2mpyd6nqdh3c6bb9wh6";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "enums" = pkgs.stdenv.mkDerivation {
        name = "enums";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-enums.git";
          rev = "9c3ec61d03c04642af91e2ac72500cdd6009bd98";
          sha256 = "0jd4a9sjg1jvzgx5iq9l2n0dh1agn00gbx25pclpbnqsx3mxw5da";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-atom" = pkgs.stdenv.mkDerivation {
        name = "erl-atom";
        version = "v1.2.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-erl-atom.git";
          rev = "4c080679047d6cb166d8a08c2fdcd6d13e480532";
          sha256 = "07b7dd1c63gs21wc65xf0m8sxq83d8fx0spwv27ixknzs98274wl";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-binary" = pkgs.stdenv.mkDerivation {
        name = "erl-binary";
        version = "v0.6.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-erl-binary.git";
          rev = "0d91ea7615eb482bc4c31eb87722dd2f032d56b6";
          sha256 = "1w9gw3g807lkhrf4mcbr0py26dqz9458dk5wcbwv5yyjiyb6dqj2";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-cowboy" = pkgs.stdenv.mkDerivation {
        name = "erl-cowboy";
        version = "v0.11.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-erl-cowboy";
          rev = "f1e3c71405f6b6d2f38086eb7ece8e197f5f8bd2";
          sha256 = "1img8xv1phw5v5mjmdldkgvfzlbxkawv8yfsy78yfk9d88j28nnk";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-kernel" = pkgs.stdenv.mkDerivation {
        name = "erl-kernel";
        version = "v0.0.3";
        src = pkgs.fetchgit {
          url = "https://github.com/id3as/purescript-erl-kernel.git";
          rev = "fb4794817149b43e89106073d910d4f8c65e5cbd";
          sha256 = "0crnby2892h89yfzgdfgi7iffp6knhyri7dnknnlbmrq5l4a0i1v";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-lists" = pkgs.stdenv.mkDerivation {
        name = "erl-lists";
        version = "v4.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-erl-lists.git";
          rev = "dbff22cb1f3e4eb243baf6d2882fc5738047b26a";
          sha256 = "1d35q091y2x86hblsd55jzr8dc25gzzwzz8lsjlln9ps11gibbsl";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-logger" = pkgs.stdenv.mkDerivation {
        name = "erl-logger";
        version = "v0.0.3";
        src = pkgs.fetchgit {
          url = "https://github.com/id3as/purescript-erl-logger.git";
          rev = "0f71204441e17db5dd9a2a6efb0f5be9840e8360";
          sha256 = "1q34l0qqx0y4zhi3gnww29spnsfdq8d80q8dj5s6q9pl8q6cz1d4";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-maps" = pkgs.stdenv.mkDerivation {
        name = "erl-maps";
        version = "v0.5.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-erl-maps.git";
          rev = "7157f6b568b9c317c02ee17ed771bd979af0d3fe";
          sha256 = "0xnv1r4f158h2m1aq7xq7a3h43a49mw03p8z7c3n0nxv819shry2";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-modules" = pkgs.stdenv.mkDerivation {
        name = "erl-modules";
        version = "v0.1.6";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-erl-modules.git";
          rev = "79ee9a4c35f798cc00f1bf35dba83e7aeaba4f2a";
          sha256 = "0m5amqd8mcbrmdxv5n8abg4dmhriyfflcacgvca36jp1qia5b90x";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-otp-types" = pkgs.stdenv.mkDerivation {
        name = "erl-otp-types";
        version = "v0.0.2";
        src = pkgs.fetchgit {
          url = "https://github.com/id3as/purescript-erl-otp-types.git";
          rev = "31a3d7c1581247679b3bc11012bb3a59fad9f9b9";
          sha256 = "10ma05dwkkmbd89wc7srxl60085j1q9dkn4vgd3sm0g6k9ir3w5k";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-pinto" = pkgs.stdenv.mkDerivation {
        name = "erl-pinto";
        version = "v0.2.0";
        src = pkgs.fetchgit {
          url = "https://github.com/id3as/purescript-erl-pinto.git";
          rev = "3851bfe52f49f713ce0818c47597bfb888c56544";
          sha256 = "051v3jkd69gaqs5icmxlcx87y88cp79irjmi9825bl15n1b7j6z2";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-process" = pkgs.stdenv.mkDerivation {
        name = "erl-process";
        version = "v3.3.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-erl-process.git";
          rev = "5eacc3a23626aed8c6036560139642122e9b8c9b";
          sha256 = "084glf8lx8j8r02qsnmx0m4w6lslvzffkzsp1z3vp5rcsval9gmn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-ranch" = pkgs.stdenv.mkDerivation {
        name = "erl-ranch";
        version = "v0.0.2";
        src = pkgs.fetchgit {
          url = "https://github.com/id3as/purescript-erl-ranch.git";
          rev = "1eda110f273339e19fc7e8d5dc6f738b0cbf547a";
          sha256 = "0nkagcqfxwh6hr5lid4vn5rs7qj2vbaaw7j0lvlz83xk8cdd6a8r";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-simplebus" = pkgs.stdenv.mkDerivation {
        name = "erl-simplebus";
        version = "v0.0.3";
        src = pkgs.fetchgit {
          url = "https://github.com/id3as/purescript-erl-simplebus.git";
          rev = "b5fcf28b4e193ba3eae5e47a0ac6c55320ed7885";
          sha256 = "0kkzqxcm3qpc2svabzfd308f0jzx4g0gbf4lzk6yk791j8c813kn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-ssl" = pkgs.stdenv.mkDerivation {
        name = "erl-ssl";
        version = "v0.0.2";
        src = pkgs.fetchgit {
          url = "https://github.com/id3as/purescript-erl-ssl.git";
          rev = "72a352ca24f7eab5a17db545940c0a070e250c73";
          sha256 = "19imc9w83li9kdbfpd6yjr4ss029all0g2kk2qmd07si44qq509s";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-stetson" = pkgs.stdenv.mkDerivation {
        name = "erl-stetson";
        version = "v0.13.0";
        src = pkgs.fetchgit {
          url = "https://github.com/id3as/purescript-erl-stetson.git";
          rev = "4aa57d93747d15a550ccdefc8146f8c1979e1e1c";
          sha256 = "1ayxliv0yihmvyv11khx2zl8fp6gxy10my7cv0wavsprnv6cxsb1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-tuples" = pkgs.stdenv.mkDerivation {
        name = "erl-tuples";
        version = "v3.3.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-erl-tuples.git";
          rev = "4a54940fd9f2fc3f8f32cf24fa82e5523ad00922";
          sha256 = "1jmvwxkj094rlcan3cnx0i3zigxdbysfhn5d1567ww7fzic4ryna";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "erl-untagged-union" = pkgs.stdenv.mkDerivation {
        name = "erl-untagged-union";
        version = "v0.0.2";
        src = pkgs.fetchgit {
          url = "https://github.com/id3as/purescript-erl-untagged-union.git";
          rev = "781b2894f9ffcc91b7aea482e435bb9284596f62";
          sha256 = "12g02r4fhvav2q2qr8wbmp90m6akij2w5d9jflaipfr4ydgxjgn5";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "exceptions" = pkgs.stdenv.mkDerivation {
        name = "exceptions";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-exceptions.git";
          rev = "e57e9598bc327f4e8301136e0af53335fbb1973f";
          sha256 = "06bvv7sb4a42bgcfaxjibgkbr6znkgqjaw7d2y2jmk39nzianlij";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "exists" = pkgs.stdenv.mkDerivation {
        name = "exists";
        version = "v5.1.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-exists.git";
          rev = "c34820f8b2d15be29abdd5097c3d636f5df8f28c";
          sha256 = "15qp52cpp2yvxihkzfmn6gabyvx5s6iz5lafvqhyfgp4wfnz0bds";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "filterable" = pkgs.stdenv.mkDerivation {
        name = "filterable";
        version = "v3.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-filterable.git";
          rev = "0b9b0994704f29e75072e6b3e6b8658b93b35ab8";
          sha256 = "1sj0r49pzkiibrin28p2ikh3z0884kzqa9p6glzh5hxh6smx8ihb";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foldable-traversable" = pkgs.stdenv.mkDerivation {
        name = "foldable-traversable";
        version = "v5.0.1-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-foldable-traversable.git";
          rev = "444a611d64800a82259b9c22999330b6a7b48a3d";
          sha256 = "0hmmx4l2ryqyqyb83iqx898dplyxgbzcqp0ibibr17x5d9bxwr68";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foreign" = pkgs.stdenv.mkDerivation {
        name = "foreign";
        version = "v6.0.1-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-foreign.git";
          rev = "91f2e6c9950db6bcab673b45f6ebd89305e97728";
          sha256 = "0warmjk4ywbzax8ik3wxkg2c8aqq16lbmr3myyhy9vpm4ckr6pcy";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "functions" = pkgs.stdenv.mkDerivation {
        name = "functions";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-functions.git";
          rev = "6f0854f056b5295835db2cc3d06bf8763c181536";
          sha256 = "122rijqvfxgrsljsvyah6jihb8cdsf083i0cx1d4pi664hr6y59j";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "functors" = pkgs.stdenv.mkDerivation {
        name = "functors";
        version = "v4.1.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-functors.git";
          rev = "e936f7a8d2ec53a344c478ccada5add93273848c";
          sha256 = "0i1x14r54758s5jx5d7zy4l07mg6gabljadgybldnbpmdqk6b966";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "gen" = pkgs.stdenv.mkDerivation {
        name = "gen";
        version = "v3.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-gen.git";
          rev = "85c369f56545a3de834b7e7475a56bc9193bb4b4";
          sha256 = "1h396rqn1fc2c155i58vnaksqjrpajly128ah6wq1w426vwr1vrf";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "identity" = pkgs.stdenv.mkDerivation {
        name = "identity";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-identity.git";
          rev = "5c150ac5ee4fa6f145932f6322a1020463dae8e9";
          sha256 = "0a58y71ihvb5b7plnn2sxsbphqzd9nzfafak4d5a576agn76q0ql";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "integers" = pkgs.stdenv.mkDerivation {
        name = "integers";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-integers.git";
          rev = "5549373344321575727cc1b3526ee946cff77a43";
          sha256 = "0bgrk1lngsnkkwvg3clwmbm3gl5ipwggi6wlmrigdpflb59dci2d";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "invariant" = pkgs.stdenv.mkDerivation {
        name = "invariant";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-invariant.git";
          rev = "c421b49dec7a1511073bb408a08bdd8c9d17d7b1";
          sha256 = "0vwkbh7kv00g50xjgvxc0mv5b99mrj6q0sxznxwk32hb9hkbhy5l";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "js-uri" = pkgs.stdenv.mkDerivation {
        name = "js-uri";
        version = "v2.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-js-uri.git";
          rev = "943ae2cd2cf81e62a658e89ab27cca7754a0fadd";
          sha256 = "19namsnxn1gr0d5d9zhsf2qijn61755ispr5cgaj4nbyd9vmsrxv";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "lazy" = pkgs.stdenv.mkDerivation {
        name = "lazy";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-lazy.git";
          rev = "11a8a4fa99ef88daf36458b163010179c633168e";
          sha256 = "0z258l76xhvjav0jxbyv3n3n8fqmhkgg5204ns2bchm3231cs818";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "lists" = pkgs.stdenv.mkDerivation {
        name = "lists";
        version = "v6.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-lists.git";
          rev = "6383c4f202b3f69474f9f7da182c2d42fcc3111c";
          sha256 = "0xmg918s3mqvfvwgjfqcs1yvcz6hy2n7h3ygqz2iyvk868gz25qs";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "math" = pkgs.stdenv.mkDerivation {
        name = "math";
        version = "v3.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-math.git";
          rev = "c4760c2620980dbd7168b17ed21dfab12b8c5b39";
          sha256 = "18yw3ni2a5hjcdrk5v4j9hwdccam5vrifcmcyapailbp4dmz8zrq";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "maybe" = pkgs.stdenv.mkDerivation {
        name = "maybe";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-maybe.git";
          rev = "8e96ca0187208e78e8df6a464c281850e5c9400c";
          sha256 = "0vyk3r9gklvv7awzpph7ra53zxxbin1ngmqflb5vvr2365v5xyqy";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "newtype" = pkgs.stdenv.mkDerivation {
        name = "newtype";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-newtype.git";
          rev = "7b292fcd2ac7c4a25d7a7a8d3387d0ee7de89b13";
          sha256 = "1fgzbxslckva2psn0sia30hfakx8xchz3wx2kkh3w8rr4nn2py8v";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "nonempty" = pkgs.stdenv.mkDerivation {
        name = "nonempty";
        version = "v6.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-nonempty.git";
          rev = "d3e91e3d6e06e5bdcc5b2c21c8e5d0f9b946bb9e";
          sha256 = "0azk1jrpqnjf2i97lcp63wcm31c4hddklp1mfmdan27zap3zqyjm";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "nullable" = pkgs.stdenv.mkDerivation {
        name = "nullable";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-nullable.git";
          rev = "22736994306a9b4568cbc610640c61e5976d01ea";
          sha256 = "1157faic08vl7mwflr4hk0crsslly56rbzq6c3ndivg0a16h2cb1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "numbers" = pkgs.stdenv.mkDerivation {
        name = "numbers";
        version = "v8.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-numbers.git";
          rev = "5446bc018f2970d91a8573c3424bba0b59305a21";
          sha256 = "110krirqhx3aawy7g4lhlcggksxs6hk2naklixmhvnpmh3nwas3w";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "ordered-collections" = pkgs.stdenv.mkDerivation {
        name = "ordered-collections";
        version = "v2.0.2-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-ordered-collections.git";
          rev = "8f9fdc347282cc952241c2f38bd98552caf4a25a";
          sha256 = "03z33c8z2q0jiibkwv5r3kjyzq1z115bvlijlf4iqr3i955irhzq";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "orders" = pkgs.stdenv.mkDerivation {
        name = "orders";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-orders.git";
          rev = "c25b7075426cf82bcb960495f28d2541c9a75510";
          sha256 = "0wwy3ycjll0s590ra35zf5gjvs86w97rln09bj428axhg7cvfl0a";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "partial" = pkgs.stdenv.mkDerivation {
        name = "partial";
        version = "v3.0.0-erl2";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-partial.git";
          rev = "6fe347eb3a36c70cacd4aeb581b5748a9d5035aa";
          sha256 = "08sn8vfdd0g2cpr4ygib8kf2ak6qncdq3vm0d7j14bk1fck1jwrk";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "prelude" = pkgs.stdenv.mkDerivation {
        name = "prelude";
        version = "v5.0.1-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-prelude.git";
          rev = "75a86f361270985ae983b59d4a69c0513b7f1cb1";
          sha256 = "0dgkxk8dhgpgr4z0j7r6317drcl5kl5pmi3a8csr4vs52cxj97dl";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "profunctor" = pkgs.stdenv.mkDerivation {
        name = "profunctor";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-profunctor.git";
          rev = "4551b8e437a00268cc9b687cbe691d75e812e82b";
          sha256 = "0fvd2xiv77sp4jd4spgdp4i9812p6pdzzbg4pa96mbr0h19jf39c";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "psci-support" = pkgs.stdenv.mkDerivation {
        name = "psci-support";
        version = "v5.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-psci-support.git";
          rev = "f26fe8266a63494080476333e22f971404ea8846";
          sha256 = "16vhf8hapd7rcgmafmjpiq7smhzdh3300f2idk1q4kk01yxn8ddj";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "record" = pkgs.stdenv.mkDerivation {
        name = "record";
        version = "v3.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-record.git";
          rev = "539eb726cd7bdfcd95bf8bca20b3aed993006919";
          sha256 = "1f3q4f5awcb1vwk8k5qnqfn2pqcb7vki0d33wn4b4g7nk7l4qc2k";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "refs" = pkgs.stdenv.mkDerivation {
        name = "refs";
        version = "v5.0.0-erl2";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-refs.git";
          rev = "1a921991d2c0900c4582d69586bfbd5ce3d53952";
          sha256 = "1b78dsfmg6g69f9k3j1y80bw2h19c4i2xx353k4dq9rlgvvbdi9k";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "routing-duplex" = pkgs.stdenv.mkDerivation {
        name = "routing-duplex";
        version = "v0.5.0";
        src = pkgs.fetchgit {
          url = "https://github.com/natefaubion/purescript-routing-duplex.git";
          rev = "34963d57ec67004a0683aaf3002929affdc3962d";
          sha256 = "05cw886qy4wqs8fsjcmk2xypm4yda6xz49frajngy9d0l60wlnk1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "safe-coerce" = pkgs.stdenv.mkDerivation {
        name = "safe-coerce";
        version = "v1.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-safe-coerce.git";
          rev = "e719defd227d932da067a1f0d62a60b3d3ff3637";
          sha256 = "0m942lc23317izspz1sxw957mwl9yb9bgk8dh23f7b3a8w9hh8ff";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "simple-json" = pkgs.stdenv.mkDerivation {
        name = "simple-json";
        version = "baad5dd0d613df6fb2f054fd241d46e11a92e181";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-simple-json.git";
          rev = "baad5dd0d613df6fb2f054fd241d46e11a92e181";
          sha256 = "1d09fd1a86gxps9ilw5qy0f4ihbn2qk5bc05ckg730w6xj0i6qp0";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "strings" = pkgs.stdenv.mkDerivation {
        name = "strings";
        version = "v5.0.0-erl2";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-strings.git";
          rev = "82ee15ccdc9d37238e4a57edbb74b135bbe2315a";
          sha256 = "1pr71fvvrq9g9bc45h4lcgd28bq71cxx0am6abj6i2qyj7533is7";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "tailrec" = pkgs.stdenv.mkDerivation {
        name = "tailrec";
        version = "v5.0.1-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-tailrec.git";
          rev = "a865d0787fef54e7350d8c1e8d2e9ed94fae47b7";
          sha256 = "1jjl2q2hyhjcdxpamzr1cdlxhmq2bl170x5p3jajb9zgwkqx0x22";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "transformers" = pkgs.stdenv.mkDerivation {
        name = "transformers";
        version = "v5.2.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-transformers.git";
          rev = "1e5d4193b38c613c97ea1ebdb721c6b94cd8c50a";
          sha256 = "0lggimnq016v98ib6h68gnciraambxrfqm2s033wm34srcy8xs06";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "tuples" = pkgs.stdenv.mkDerivation {
        name = "tuples";
        version = "v6.0.1";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-tuples.git";
          rev = "d4fe8ffe9e8c512111ee0bc18a6ba0fd056a6773";
          sha256 = "0s2ar2gih4r34km8r8dqngh21s8899yb93mb7mips08ndy3ajq3a";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "type-equality" = pkgs.stdenv.mkDerivation {
        name = "type-equality";
        version = "v4.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-type-equality.git";
          rev = "f7644468f22ed267a15d398173d234fa6f45e2e0";
          sha256 = "126pg4zg3bsrn8dzvv75xp586nznxyswzgjlr7cag3ij3j1z0kl0";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "typelevel-prelude" = pkgs.stdenv.mkDerivation {
        name = "typelevel-prelude";
        version = "v6.0.0";
        src = pkgs.fetchgit {
          url = "https://github.com/purescript/purescript-typelevel-prelude.git";
          rev = "83ddcdb23d06c8d5ea6196596a70438f42cd4afd";
          sha256 = "1vwf3yhn8mir5y41wvlyszkgd5fxvrcyfd0l8cn20c8vfq36yzgk";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "unfoldable" = pkgs.stdenv.mkDerivation {
        name = "unfoldable";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-unfoldable.git";
          rev = "5d3b6ac48757c9aa93f6410f86266034fd510599";
          sha256 = "1sqjwwwlw131bp8d57i1gf1jld8ynnjz3al9lk8bva6hb5ji07ci";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "unsafe-coerce" = pkgs.stdenv.mkDerivation {
        name = "unsafe-coerce";
        version = "v5.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-unsafe-coerce.git";
          rev = "7150d261d40cd92112e8c2064124c5682627f137";
          sha256 = "0bgsswq08w8sbydmdq3x0z6xcmdf8cgdcxcw2dwqz45kshsxqi1w";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "unsafe-reference" = pkgs.stdenv.mkDerivation {
        name = "unsafe-reference";
        version = "v4.0.0-erl1";
        src = pkgs.fetchgit {
          url = "https://github.com/purerl/purescript-unsafe-reference.git";
          rev = "464ee74d0c3ef50e7b661c13399697431f4b6251";
          sha256 = "1v8qyf59wigrb3pv3f7bir12asj21ickjqanykfqlm417nzx9hqn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "variant" = pkgs.stdenv.mkDerivation {
        name = "variant";
        version = "v7.0.3";
        src = pkgs.fetchgit {
          url = "https://github.com/natefaubion/purescript-variant.git";
          rev = "3f12411ede5edd342d25340c1babce9ae81d6793";
          sha256 = "1q2pky3gf177ihy2zjzqvp1cj18ycaki9vm4ghw18p7hf256lqmc";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

  };

  cpPackage = pkg:
    let
      target = ".spago/${pkg.name}/${pkg.version}";
    in ''
      if [ ! -e ${target} ]; then
        echo "Installing ${target}."
        mkdir -p ${target}
        cp --no-preserve=mode,ownership,timestamp -r ${toString pkg.outPath}/* ${target}
      else
        echo "${target} already exists. Skipping."
      fi
    '';

  getGlob = pkg: ''".spago/${pkg.name}/${pkg.version}/src/**/*.purs"'';

  getStoreGlob = pkg: ''"${pkg.outPath}/src/**/*.purs"'';

in {
  inherit inputs;

  installSpagoStyle = pkgs.writeShellScriptBin "install-spago-style" ''
      set -e
      echo installing dependencies...
      ${builtins.toString (builtins.map cpPackage (builtins.attrValues inputs))}
      echo "echo done."
  '';

  buildSpagoStyle = pkgs.writeShellScriptBin "build-spago-style" ''
      set -e
      echo building project...
      purs compile ${builtins.toString (builtins.map getGlob (builtins.attrValues inputs))} "$@"
      echo done.
  '';

  buildFromNixStore = pkgs.writeShellScriptBin "build-from-store" ''
      set -e
      echo building project using sources from nix store...
      purs compile ${builtins.toString (
        builtins.map getStoreGlob (builtins.attrValues inputs))} "$@"
      echo done.
  '';

  mkBuildProjectOutput =
    { src, purs }:

    pkgs.stdenv.mkDerivation {
      name = "build-project-output";
      src = src;

      buildInputs = [ purs ];

      installPhase = ''
        mkdir -p $out
        purs compile "$src/**/*.purs" ${builtins.toString
          (builtins.map
            (x: ''"${x.outPath}/src/**/*.purs"'')
            (builtins.attrValues inputs))}
        mv output $out
      '';
    };
}
